In [5]:
import numpy as np
desc1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
desc2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
distances = np.linalg.norm(desc1[0, :] - desc2, axis=2)
print (distances)


AxisError: axis 2 is out of bounds for array of dimension 2

In [1]:
        desc = np.zeros((len(keypoints), 5 * 5))

    desc

IndentationError: unexpected indent (<ipython-input-1-41945482ed81>, line 3)

In [7]:
desc = np.zeros((3, 5 * 5))
desc


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
import numpy as np

In [9]:
print(desc.shape)

(3, 25)


In [13]:
keypoint = np.array([1,5,5,3,3,6,6,8,9])

In [15]:
for i,f in enumerate(keypoint):
    #print(i);
    print(f);

1
5
5
3
3
6
6
8
9


In [16]:
f=enumerate(keypoint)

In [19]:
list(f)

[(0, 1), (1, 5), (2, 5), (3, 3), (4, 3), (5, 6), (6, 6), (7, 8), (8, 9)]

In [18]:
print(f)

In [31]:
patch = np.zeros((3,5))

In [34]:
patch

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
i=0;
for u,v in np.ndindex(patch.shape):
    patch[u][v]=i;
    i += 1;

In [36]:
patch

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [43]:
patch.shape

(3, 5)

In [42]:
patch.reshape(1,-1)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14.]])

In [39]:
a=np.array([1,2,3,4,5])

In [40]:
a

array([1, 2, 3, 4, 5])

In [52]:
a = np.array([[1, 2], [3, 4]])
mu=np.mean(a);
sigma = np.std(a);

AttributeError: type object 'numpy.float32' has no attribute 'array'

In [48]:
for u,v in np.ndindex(a.shape):
    a[u][v] = (a[u][v]-mu)/sigma

In [49]:
a

array([[-1,  0],
       [ 0,  1]])